# 베이스 이미지로 nginx를 사용합니다.
FROM nginx:latest

# 컨테이너 내부의 Nginx 설정 파일을 복사합니다.
COPY default.conf /etc/nginx/conf.d/default.conf

# 컨테이너 내부의 HTML 파일을 복사합니다.
COPY home.html /usr/share/nginx/html/home.html
COPY userInfo.html /usr/share/nginx/html/userInfo.html

# Nginx 서버를 실행합니다.
CMD ["nginx", "-g", "daemon off;"]

EXPOSE 8080
