FROM nginx:latest

WORKDIR /app

COPY static/ /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf
#COPY default.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
