FROM nginx:latest

WORKDIR /app

COPY static/home.html /usr/share/nginx/html/home.html
COPY static/style.css /usr/share/nginx/html/style.css

COPY default.conf /etc/nginx/conf.d/default.conf
#COPY default.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
